
```{r}
install.packages("R.utils")
library(R.utils)
```

```{r}
# gunzip the files
R.utils::gunzip("train-images-idx3-ubyte.gz")
R.utils::gunzip("train-labels-idx1-ubyte.gz")
R.utils::gunzip("t10k-images-idx3-ubyte.gz")
R.utils::gunzip("t10k-labels-idx1-ubyte.gz")
```

```{r}
# helper function for visualization
show_digit = function(arr784, col = gray(12:1 / 12), ...) {
  image(matrix(as.matrix(arr784[-785]), nrow = 28)[, 28:1], col = col, ...)
}
```

```{r}
# load image files
load_image_file = function(filename) {
  ret = list()
  f = file(filename, 'rb')
  readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  n    = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  nrow = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  ncol = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  x = readBin(f, 'integer', n = n * nrow * ncol, size = 1, signed = FALSE)
  close(f)
  data.frame(matrix(x, ncol = nrow * ncol, byrow = TRUE))
}
```

```{r}
# load label files
load_label_file = function(filename) {
  f = file(filename, 'rb')
  readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  n = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  y = readBin(f, 'integer', n = n, size = 1, signed = FALSE)
  close(f)
  y
}
```

```{r}
# load images
image_train = load_image_file("E:/GitHub/divhacks-IBM-challenge-chunziwang/data/train-images-idx3-ubyte")
image_test  = load_image_file("E:/GitHub/divhacks-IBM-challenge-chunziwang/data/t10k-images-idx3-ubyte")

# load labels
image_train$y = as.factor(load_label_file("E:/GitHub/divhacks-IBM-challenge-chunziwang/data/train-labels-idx1-ubyte"))
image_test$y  = as.factor(load_label_file("E:/GitHub/divhacks-IBM-challenge-chunziwang/data/t10k-labels-idx1-ubyte"))

# view test image
show_digit(image_train[10000, ])
```

```{r}
head(image_train$y,10)
```


